DROP TABLE IF EXISTS INV_INVENTORY;
CREATE TABLE INV_INVENTORY (
  ID VARCHAR(255) NOT NULL COMMENT 'pk',
  INVENTORY_NAME VARCHAR(255) COMMENT 'ชื่อสิงค้า',
  USER_NAME VARCHAR(255) COMMENT 'ชื่อผู้ใช้'
);
ALTER TABLE INV_INVENTORY ADD CONSTRAINT INV_INVENTORY_PK PRIMARY KEY (ID);

INSERT INTO INV_INVENTORY VALUES('x01' , 'Ipad' , 'สมชาย');
INSERT INTO INV_INVENTORY VALUES('x02' , 'Notebook' , 'สายลม');
INSERT INTO INV_INVENTORY VALUES('x03' , 'Ipad' , 'สมร');
INSERT INTO INV_INVENTORY VALUES('x04' , 'Ipad' , 'สมหญิง');
INSERT INTO INV_INVENTORY VALUES('x05' , 'Notebook' , 'พิศมัส');
INSERT INTO INV_INVENTORY VALUES('x06' , 'Notebook' , 'วลัย');
INSERT INTO INV_INVENTORY VALUES('x07' , 'Notebook' , 'ใจดี');
INSERT INTO INV_INVENTORY VALUES('x08' , 'Notebook' , 'ชาติชาย');
INSERT INTO INV_INVENTORY VALUES('x09' , 'Notebook' , 'ทดสอบ');
INSERT INTO INV_INVENTORY VALUES('x10' , 'Notebook' , 'กนก');
INSERT INTO INV_INVENTORY VALUES('x11' , 'Notebook' , 'กร');
INSERT INTO INV_INVENTORY VALUES('x12' , 'Ipad' , 'ขร');
INSERT INTO INV_INVENTORY VALUES('x13' , 'Notebook' , 'คำ');

